/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dividendTokenSol from "./dividendToken.sol";
export type { dividendTokenSol };
import type * as dividendTokenDeployerSol from "./dividendTokenDeployer.sol";
export type { dividendTokenDeployerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as tokenRegistrySol from "./tokenRegistry.sol";
export type { tokenRegistrySol };
