/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIceCreamSwapFactory } from "./IIceCreamSwapFactory";
export type { IIceCreamSwapRouter } from "./IIceCreamSwapRouter";
export type { ITokenRegistry } from "./ITokenRegistry";
