/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IIceCreamSwapFactory,
  IIceCreamSwapFactoryInterface,
} from "../../../contracts/interfaces/IIceCreamSwapFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "createPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIceCreamSwapFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IIceCreamSwapFactoryInterface {
    return new utils.Interface(_abi) as IIceCreamSwapFactoryInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IIceCreamSwapFactory {
    return new Contract(address, _abi, signerOrProvider) as IIceCreamSwapFactory;
  }
}
